"""
Multi-Tenancy Security & Data Isolation Test Suite
Validates strict server-side tenant isolation, role-based access, and cross-tenant protection.
"""

import pytest
from datetime import date, timedelta
from app.models.organization import Organization, OrganizationMember
from app.models.cost import CostRecord
from app.models.report import Report
from app.models.user import User
from app.auth.security import create_access_token


def test_get_my_organizations(client, user_headers):
    """Verifies that a user can list their organization memberships."""
    resp = client.get("/api/v1/organizations/me", headers=user_headers)
    assert resp.status_code == 200
    data = resp.json()
    assert data["success"] is True
    assert isinstance(data["data"], list)
    assert len(data["data"]) >= 1
    assert data["data"][0]["organization_slug"] == "default-org"


def test_create_organization(client, user_headers):
    """Verifies creating a new tenant organization."""
    payload = {"name": "Acme Corp", "slug": "acme-corp"}
    resp = client.post("/api/v1/organizations", json=payload, headers=user_headers)
    assert resp.status_code == 200
    data = resp.json()["data"]
    assert data["organization_name"] == "Acme Corp"
    assert data["organization_slug"] == "acme-corp"


def test_tenant_header_unauthorized_access(client, user_headers):
    """Verifies that passing an X-Organization-ID for an unjoined org returns 403 Forbidden."""
    headers = {**user_headers, "X-Organization-ID": "non-existent-or-unauthorized-org-uuid"}
    resp = client.get("/api/v1/dashboard/summary", headers=headers)
    assert resp.status_code == 403
    assert "Forbidden" in resp.json()["error"]["message"] or "Access" in resp.json()["error"]["message"] or "denied" in resp.json()["error"]["message"]


def test_cross_tenant_cost_isolation(client, db_session, user_headers):
    """
    Verifies that cost data belonging to Tenant B is never returned to Tenant A.
    """
    # 1. Get default org (Tenant A)
    default_org = db_session.query(Organization).filter(Organization.slug == "default-org").first()
    assert default_org is not None

    # 2. Create Tenant B and add user to Tenant B
    tenant_b = Organization(name="Tenant B Corp", slug="tenant-b-corp")
    db_session.add(tenant_b)
    db_session.commit()

    member_b = OrganizationMember(
        organization_id=tenant_b.id,
        user_id="test-user-uuid",
        role="OWNER",
        status="ACTIVE",
    )
    db_session.add(member_b)

    # Add cost record exclusive to Tenant B
    cost_b = CostRecord(
        organization_id=tenant_b.id,
        provider="AWS",
        date=date.today(),
        account_id="999999999999",
        account_name="Tenant B Account",
        region="us-west-2",
        service="Amazon S3",
        service_category="Storage",
        usage_quantity=100.0,
        usage_unit="GB",
        cost=5000.0,
        currency="USD",
        tags={"Tenant": "B"},
        idempotency_key="tenant-b-s3-record-1",
    )
    db_session.add(cost_b)
    db_session.commit()

    # 3. Query costs under Tenant A context -> Should NOT see Tenant B account 999999999999 records
    headers_a = {**user_headers, "X-Organization-ID": default_org.id}
    resp_a = client.get("/api/v1/costs?account_id=999999999999", headers=headers_a)
    assert resp_a.status_code == 200
    a_records = resp_a.json()["data"]
    assert len(a_records) == 0

    # 4. Query costs under Tenant B context -> Should see Tenant B S3 record
    headers_b = {**user_headers, "X-Organization-ID": tenant_b.id}
    resp_b = client.get("/api/v1/costs?account_id=999999999999", headers=headers_b)
    assert resp_b.status_code == 200
    b_records = resp_b.json()["data"]
    assert len(b_records) == 1
    assert b_records[0]["service"] == "Amazon S3"
    assert float(b_records[0]["cost"]) == 5000.0


def test_report_download_idor_protection(client, db_session, user_headers):
    """
    Verifies IDOR protection: User in Tenant A cannot download a report generated by Tenant B.
    """
    default_org = db_session.query(Organization).filter(Organization.slug == "default-org").first()
    tenant_b = db_session.query(Organization).filter(Organization.slug == "tenant-b-corp").first()
    if not tenant_b:
        tenant_b = Organization(name="Tenant B Corp", slug="tenant-b-corp")
        db_session.add(tenant_b)
        db_session.commit()

    # Create dummy report for Tenant B
    report_b = Report(
        id="report-b-secret-uuid",
        organization_id=tenant_b.id,
        name="Tenant B Secret Financial Report",
        format="csv",
        start_date=date.today() - timedelta(days=7),
        end_date=date.today(),
        account_id="all",
        file_path="/tmp/fake_tenant_b_report.csv",
        file_size_bytes=100,
        status="COMPLETED",
        created_by="test-admin-uuid",
    )
    db_session.add(report_b)
    db_session.commit()

    # Attempt to download report_b using Tenant A context
    headers_a = {**user_headers, "X-Organization-ID": default_org.id}
    resp = client.get(f"/api/v1/reports/{report_b.id}/download", headers=headers_a)
    assert resp.status_code in (404, 403)


def test_organization_switch(client, db_session, user_headers):
    """Verifies organization switching endpoint."""
    default_org = db_session.query(Organization).filter(Organization.slug == "default-org").first()
    resp = client.post(
        "/api/v1/organizations/switch",
        json={"organization_id": default_org.id},
        headers=user_headers,
    )
    assert resp.status_code == 200
    data = resp.json()["data"]
    assert data["organization_id"] == default_org.id
