"""
CloudFormation & Terraform Template Generator for Cloud Cost Intelligence Cross-Account IAM Role.

Customers deploy this template in THEIR OWN AWS account to allow Cloud Cost Intelligence
to perform cost explorer queries and rightsizing recommendations via temporary STS AssumeRole credentials.
"""

import json
from typing import Dict, Any


def get_trust_policy(external_id: str, platform_assume_role_arn: str = "arn:aws:iam::783764605244:role/CloudCostAssumeRole") -> Dict[str, Any]:
    """Generates IAM Trust Policy restricting AssumeRole access to the platform and tenant ExternalID."""
    return {
        "Version": "2012-10-17",
        "Statement": [
            {
                "Sid": "CloudCostAssumeRole",
                "Effect": "Allow",
                "Principal": {
                    "AWS": platform_assume_role_arn
                },
                "Action": "sts:AssumeRole",
                "Condition": {
                    "StringEquals": {
                        "sts:ExternalId": external_id
                    }
                }
            }
        ]
    }


def generate_cfn_template(external_id: str, platform_assume_role_arn: str = "arn:aws:iam::783764605244:role/CloudCostAssumeRole") -> Dict[str, Any]:
    """Returns CloudFormation template (Python dict) to deploy read-only scanner role in customer AWS account."""
    return {
        "AWSTemplateFormatVersion": "2010-09-09",
        "Description": (
            "Cloud Cost Intelligence - Read-Only FinOps Cross-Account Scanner Role. "
            "Deploys CloudCostScannerRole to enable automated cost tracking, rightsizing recommendations, "
            "and budget monitoring using secure temporary STS credentials."
        ),
        "Parameters": {
            "ExternalId": {
                "Type": "String",
                "Default": external_id,
                "Description": "Unique tenant security token generated by Cloud Cost Intelligence. Do not modify.",
                "AllowedPattern": "[a-f0-9\\-]{36}",
            },
        },
        "Resources": {
            "CloudCostScannerRole": {
                "Type": "AWS::IAM::Role",
                "Properties": {
                    "RoleName": "CloudCostScannerRole",
                    "Description": "Read-only IAM Role assumed by Cloud Cost Intelligence for FinOps cost monitoring.",
                    "AssumeRolePolicyDocument": {
                        "Version": "2012-10-17",
                        "Statement": [
                            {
                                "Sid": "CloudCostAssumeRole",
                                "Effect": "Allow",
                                "Principal": {
                                    "AWS": platform_assume_role_arn
                                },
                                "Action": "sts:AssumeRole",
                                "Condition": {
                                    "StringEquals": {
                                        "sts:ExternalId": {"Ref": "ExternalId"}
                                    }
                                },
                            }
                        ],
                    },
                    "ManagedPolicyArns": [
                        "arn:aws:iam::aws:policy/SecurityAudit",
                        "arn:aws:iam::aws:policy/ReadOnlyAccess",
                    ],
                    "Policies": [
                        {
                            "PolicyName": "CloudCostExplorerReadOnly",
                            "PolicyDocument": {
                                "Version": "2012-10-17",
                                "Statement": [
                                    {
                                        "Sid": "CostExplorerAndPricingRead",
                                        "Effect": "Allow",
                                        "Action": [
                                            "ce:GetCostAndUsage",
                                            "ce:GetCostForecast",
                                            "ce:GetReservationUtilization",
                                            "ce:GetReservationPurchaseRecommendation",
                                            "ce:GetRightsizingRecommendation",
                                            "ce:GetSavingsPlansPurchaseRecommendation",
                                            "ce:GetSavingsPlansUtilization",
                                            "pricing:GetProducts",
                                            "pricing:GetAttributeValues",
                                            "organizations:ListAccounts",
                                            "organizations:DescribeOrganization"
                                        ],
                                        "Resource": "*"
                                    }
                                ],
                            },
                        }
                    ],
                    "Tags": [
                        {"Key": "CreatedBy", "Value": "CloudCostIntelligence"},
                        {"Key": "Purpose", "Value": "FinOps-Cost-Monitoring"}
                    ],
                },
            }
        },
        "Outputs": {
            "RoleArn": {
                "Description": "Paste this IAM Role ARN into Cloud Cost Intelligence to complete AWS connection.",
                "Value": {"Fn::GetAtt": ["CloudCostScannerRole", "Arn"]},
                "Export": {"Name": "CloudCostScannerRoleArn"},
            },
            "ExternalId": {
                "Description": "External ID embedded in trust policy.",
                "Value": {"Ref": "ExternalId"},
            },
        },
    }


def generate_terraform_template(external_id: str, aws_account_id: str, platform_assume_role_arn: str = "arn:aws:iam::783764605244:role/CloudCostAssumeRole") -> str:
    """Returns Terraform HCL code snippet to deploy scanner role in customer AWS account."""
    return f'''# Cloud Cost Intelligence — Cross-Account FinOps Scanner Role
# Deploy in your customer AWS account ({aws_account_id})

terraform {{
  required_providers {{
    aws = {{
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }}
  }}
}}

resource "aws_iam_role" "cloudcost_scanner" {{
  name        = "CloudCostScannerRole"
  description = "Read-only role assumed by Cloud Cost Intelligence for cost analytics"

  assume_role_policy = jsonencode({{
    Version = "2012-10-17"
    Statement = [
      {{
        Sid    = "CloudCostAssumeRole"
        Effect = "Allow"
        Principal = {{
          AWS = "{platform_assume_role_arn}"
        }}
        Action = "sts:AssumeRole"
        Condition = {{
          StringEquals = {{
            "sts:ExternalId" = "{external_id}"
          }}
        }}
      }}
    ]
  }})

  tags = {{
    CreatedBy = "CloudCostIntelligence"
    Purpose   = "FinOps-Cost-Monitoring"
  }}
}}

resource "aws_iam_role_policy_attachment" "security_audit" {{
  role       = aws_iam_role.cloudcost_scanner.name
  policy_arn = "arn:aws:iam::aws:policy/SecurityAudit"
}}

resource "aws_iam_role_policy_attachment" "read_only" {{
  role       = aws_iam_role.cloudcost_scanner.name
  policy_arn = "arn:aws:iam::aws:policy/ReadOnlyAccess"
}}

output "role_arn" {{
  description = "Paste this ARN into Cloud Cost Intelligence to complete connection"
  value       = aws_iam_role.cloudcost_scanner.arn
}}
'''


def get_permissions_policy() -> Dict[str, Any]:
    """Generates IAM Permissions Policy for Cost Explorer and Pricing data access."""
    return {
        "Version": "2012-10-17",
        "Statement": [
            {
                "Sid": "CostExplorerAndPricingRead",
                "Effect": "Allow",
                "Action": [
                    "ce:GetCostAndUsage",
                    "ce:GetCostForecast",
                    "ce:GetReservationUtilization",
                    "ce:GetReservationPurchaseRecommendation",
                    "ce:GetRightsizingRecommendation",
                    "ce:GetSavingsPlansPurchaseRecommendation",
                    "ce:GetSavingsPlansUtilization",
                    "pricing:GetProducts",
                    "pricing:GetAttributeValues",
                    "organizations:ListAccounts",
                    "organizations:DescribeOrganization"
                ],
                "Resource": "*"
            }
        ]
    }


def get_manual_instructions(external_id: str, aws_account_id: str, platform_assume_role_arn: str = "arn:aws:iam::783764605244:role/CloudCostAssumeRole") -> Dict[str, Any]:
    """Returns step-by-step instructions for manual IAM console configuration."""
    return {
        "platform_assume_role_arn": platform_assume_role_arn,
        "external_id": external_id,
        "trust_policy": get_trust_policy(external_id, platform_assume_role_arn),
        "permissions_policy": get_permissions_policy(),
        "managed_policies": ["arn:aws:iam::aws:policy/SecurityAudit", "arn:aws:iam::aws:policy/ReadOnlyAccess"],
        "role_name": "CloudCostScannerRole",
        "expected_role_arn": f"arn:aws:iam::{aws_account_id}:role/CloudCostScannerRole" if aws_account_id else "arn:aws:iam::<ACCOUNT_ID>:role/CloudCostScannerRole",
        "steps": [
            f"1. Sign in to AWS Management Console for account ({aws_account_id or 'Target Account'})",
            "2. Navigate to IAM → Roles → Create role",
            "3. Select 'Custom trust policy' and paste the Trust Policy below",
            "4. Attach AWS Managed Policies: 'SecurityAudit' and 'ReadOnlyAccess'",
            "5. (Optional) Attach Custom Inline Policy for Cost Explorer API permissions",
            "6. Set Role Name to: CloudCostScannerRole",
            "7. Create role, copy Role ARN and paste below"
        ]
    }
